version: '3.8'

services:
  web:
    build:
    ports:
      - "5000:5000"
    environment:
      - DB_SERVER=192.168.1.40
      - DB_DATABASE=PORTAL_EYV
      - DB_TRUSTED=yes
      - DB_DRIVER=ODBC Driver 17 for SQL Server
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge